app <- ShinyDriver$new("../../", seed = 100, shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$setInputs(dynamic = 14)
app$snapshot()
app$setInputs(input_type = "text")
app$setInputs(dynamic = "abcd")
app$snapshot()
app$setInputs(input_type = "numeric")
app$setInputs(dynamic = 100)
app$snapshot()
app$setInputs(input_type = "checkbox")
app$setInputs(dynamic = FALSE)
app$snapshot()
app$setInputs(input_type = "checkboxGroup")
app$setInputs(dynamic = c("option1", "option2"))
app$snapshot()
app$setInputs(dynamic = "option1")
app$setInputs(dynamic = character(0))
app$snapshot()
app$setInputs(input_type = "radioButtons")
app$setInputs(dynamic = "option1")
app$snapshot()
app$setInputs(input_type = "selectInput")
app$setInputs(dynamic = "option1")
app$snapshot()
app$setInputs(input_type = "selectInput (multi)")
app$snapshot()
app$setInputs(dynamic = "option1")
app$setInputs(dynamic = character(0))
app$snapshot()
app$setInputs(input_type = "date")
app$setInputs(dynamic = "2020-01-31")
app$snapshot()
app$setInputs(input_type = "daterange")
app$setInputs(dynamic = c("2020-01-08", "2020-01-31"))
app$snapshot()
