app <- ShinyDriver$new("../../", seed = 100, shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$waitForValue("checkboxOut", iotype = "output")
app$snapshot()
app$setInputs(text = "Enter ")
app$setInputs(text = "Enter hagjhfafglak")
app$setInputs(slider2 = c(25, 87))
app$setInputs(slider2 = c(69, 87))
app$setInputs(slider1 = 100)
app$setInputs(checkGroup = c("1", "2"))
app$setInputs(checkGroup = c("1", "2", "3"))
app$setInputs(checkbox = FALSE)
app$setInputs(action = "click")
app$setInputs(action = "click")
app$snapshot()
app$setInputs(action = "click")
app$setInputs(action = "click")
app$setInputs(action = "click")
app$setInputs(action = "click")
app$setInputs(checkbox = TRUE)
app$setInputs(checkbox = FALSE)
app$setInputs(checkGroup = character(0))
app$setInputs(checkGroup = "2")
app$setInputs(checkGroup = c("2", "3"))
app$setInputs(checkGroup = "2")
app$setInputs(checkGroup = character(0))
app$setInputs(checkGroup = "1")
app$snapshot()
app$setInputs(checkGroup = character(0))
app$setInputs(checkbox = TRUE)
app$setInputs(date = "2014-01-15")
app$setInputs(date = "2014-01-30")
app$setInputs(dates = c("2019-12-19", "2019-12-05"))
app$setInputs(dates = c("2019-12-19", "2019-12-12"))
app$uploadFile(file = "cars.csv")
app$setInputs(select = "3")
app$setInputs(slider1 = 18)
app$setInputs(slider1 = 71)
app$setInputs(select = "2")
app$setInputs(select = "1")
app$setInputs(radio = "2")
app$setInputs(radio = "3")
app$setInputs(slider1 = 31)
app$setInputs(slider1 = 79)
app$setInputs(slider2 = c(0, 75))
app$setInputs(slider2 = c(0, 100))
app$setInputs(text = "More text")
app$snapshot()
