app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$waitForValue("observeEventStatus", "output")
app$snapshot()
app$setInputs(type = "silent")
app$snapshot()
app$setInputs(type = "validation")
app$snapshot()
app$setInputs(type = "error")
app$snapshot()
app$setInputs(success = "click")
app$snapshot()
app$setInputs(silent = "click")
app$snapshot()
app$setInputs(validation = "click")
app$snapshot()
