app <- ShinyDriver$new("../../", seed = 100, shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")
app$snapshot()
app$setInputs(xcol = "Petal.Length")
app$setInputs(ycol = "Petal.Width")
app$setInputs(clusters = 4)
app$setInputs(clusters = 5)
app$setInputs(clusters = 6)
app$snapshot()
