app <- ShinyDriver$new("../", seed = 100,shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(dataset = "pressure")
app$setInputs(update = "click")
app$snapshot()
app$setInputs(dataset = "cars")
app$snapshot()
app$setInputs(dataset = "pressure")
app$setInputs(update = "click")
app$setInputs(obs = 11)
app$setInputs(obs = 12)
app$setInputs(update = "click")
app$setInputs(obs = 15)
app$setInputs(obs = 14)
app$setInputs(obs = 3)
app$setInputs(obs = 2)
app$setInputs(obs = 1)
app$setInputs(obs = 0)
app$setInputs(update = "click")
app$snapshot()
