app <- ShinyDriver$new("../../", seed = 100, shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$snapshot()
app$setInputs(add = "click",wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(tabs = "Dynamic",wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(remove = "click",wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(addFoo = "click",wait_=FALSE, values_=FALSE)
app$setInputs(tabs = "Foo",wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(tabs = "Hello",wait_=FALSE, values_=FALSE)
app$setInputs(tabs = "f",wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(add = "click",wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(addFoo = "click",wait_=FALSE, values_=FALSE)
app$setInputs(tabs = "Foo",wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(remove = "click",wait_=FALSE, values_=FALSE)
app$snapshot()

