app <- ShinyDriver$new("../../", seed = 100, shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(`shinytheme-selector` = "lumen")
Sys.sleep(2)
app$snapshot()
app$setInputs(`shinytheme-selector` = "spacelab")
Sys.sleep(2)
app$snapshot()
app$setInputs(`shinytheme-selector` = "yeti")
Sys.sleep(2)
app$snapshot()
