app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(`navbar-insert` = "click")
app$setInputs(`navbar-insert` = "click")
app$setInputs(`tabset-insert` = "click")
app$setInputs(`tabset-insert` = "click")
app$setInputs(`navlist-insert` = "click")
app$setInputs(`navlist-insert` = "click")
app$setInputs(`tabset-tabset` = "A")
app$setInputs(`navlist-navlist` = "B")
app$snapshot()
app$setInputs(`navlist-remove` = "click")
app$setInputs(`tabset-remove` = "click")
app$setInputs(`tabset-hide` = "click")
app$setInputs(`navbar-remove` = "click")
app$snapshot()
app$setInputs(`navbar-navbar` = "A")
app$snapshot()
