app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$waitForValue("table_cell_clicked")
app$snapshot()
app$setInputs(inc = "click")
app$setInputs(inc = "click")
app$setInputs(inc = "click")
app$setInputs(`one-inc` = "click")
app$snapshot()
