#!/bin/bash

set -e

DOCKER_TAG="${DOCKER_TAG}"

# sso-3.6-centos7
R_VERSION=`echo "$DOCKER_TAG" | cut -d '-' -f 2`
RELEASE=`echo "$DOCKER_TAG" | cut -d '-' -f 3`

echo '<-- Showing Environment Variables'
echo "DOCKERFILE_PATH=${DOCKERFILE_PATH}"

echo ""
echo "SOURCE_BRANCH=${SOURCE_BRANCH}"
echo "SOURCE_COMMIT=${SOURCE_COMMIT}"
echo "COMMIT_MSG=${COMMIT_MSG}"
echo "DOCKER_REPO=${DOCKER_REPO}"
echo "DOCKER_TAG=${DOCKER_TAG}"
echo "R_VERSION=$R_VERSION"
echo "RELEASE=$RELEASE"
echo '-->'

docker build \
  --build-arg R_VERSION=$R_VERSION \
  --build-arg RELEASE=$RELEASE \
  # --build-arg AWS_BUILD_MACHINE=centos6.3 \
  -f $DOCKERFILE_PATH \
  -t $IMAGE_NAME \
  .
