app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(simpleTextInput = "a")
app$setInputs(simpleTextInput = "ab")
app$setInputs(simpleTextInput = "abc")
app$setInputs(simpleTextInput = "abcd")
app$setInputs(simpleTextInput = "abcd1")
app$setInputs(simpleTextInput = "abcd12")
app$setInputs(simpleTextInput = "abcd123")
app$setInputs(simpleTextInput = "abcd1234")
app$snapshot()
app$setInputs(`._bookmark_` = "click")
Sys.sleep(1)
app$snapshot()
