app <- ShinyDriver$new("../../", seed = 100, shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$uploadFile(file1 = "Rock.csv")
app$snapshot()
app$setInputs(sep = ";")
app$setInputs(sep = ",")
app$setInputs(quote = "")
app$snapshot()
app$setInputs(sep = ";")
app$setInputs(disp = "all")
app$setInputs(quote = "'")
app$setInputs(disp = "head")
app$snapshot()
