app <- ShinyDriver$new("../../", seed = 100, shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

Sys.sleep(3)
app$snapshot()
app$setInputs(year = c(1988, 2014),wait_=FALSE, values_=FALSE)
app$setInputs(year = c(2002, 2014),wait_=FALSE, values_=FALSE)
Sys.sleep(2)
app$snapshot()
app$setInputs(year = c(2008, 2014),wait_=FALSE, values_=FALSE)
app$setInputs(oscars = 1, wait_=FALSE, values_=FALSE)
Sys.sleep(2)
app$snapshot()
app$setInputs(oscars = 0, wait_=FALSE, values_=FALSE)
app$setInputs(genre = "Animation",wait_=FALSE, values_=FALSE)
app$setInputs(xvar = "Reviews",wait_=FALSE, values_=FALSE)
app$setInputs(yvar = "BoxOffice",wait_=FALSE, values_=FALSE)
Sys.sleep(2)
app$snapshot()
