library(shinytest)
app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(slider = c(17, 70))
app$setInputs(selectize = "AK")
app$setInputs(selectizeMulti = "AZ")
app$setInputs(selectizeMulti = c("AZ", "CA"))
app$setInputs(selectizeMulti = c("AZ", "CA", "CO"))
app$setInputs(date = "2020-10-23")
app$setInputs(dateRange = c("2020-07-10", "2020-10-26"))
app$setInputs(dateRange = c("2020-07-10", "2020-10-30"))
app$snapshot()
app$setInputs(inputsNav = "Basic")
app$setInputs(select = "AR")
app$setInputs(password = "super-secret")
app$setInputs(textArea = "fun")
app$setInputs(selectMulti = "AK")
app$setInputs(text = "super")
app$setInputs(check = FALSE)
app$setInputs(checkGroup = "A")
app$setInputs(checkGroup = c("A", "B"))
app$setInputs(numeric = 1)
app$setInputs(radioButtons = "B")
app$snapshot()
app$setInputs(navbar = "Tables")
app$snapshot()
app$setInputs(navbar = "Other")
app$setInputs(showDefault = "click")
app$setInputs(showMessage = "click")
app$setInputs(showWarning = "click")
app$setInputs(showError = "click")
app$snapshot()
app$setInputs(showProgress = "click")
Sys.sleep(0.75)
app$snapshot()
app$setInputs(otherNav = "Uploads & Downloads")
app$uploadFile(file = "upload-file.txt")
app$snapshot()
app$setInputs(otherNav = "Messages")
app$setInputs(showModal = "click")
app$snapshot()
