app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(text = "RStudio")
app$setInputs(select = "Michigan")
app$setInputs(date = "2020-12-24")
app$setInputs(dateRange = c("2020-12-11", "2020-12-10"))
app$setInputs(dateRange = c("2020-12-11", "2020-12-12"))
app$setInputs(slider = 0)
app$setInputs(slider = 1)
app$setInputs(checkbox = TRUE)
app$setInputs(checkboxGroup = "B")
app$setInputs(radio = "B")
app$snapshot()
app$setInputs(radio = "A")
app$setInputs(checkboxGroup = c("A", "B"))
app$setInputs(checkbox = FALSE)
app$setInputs(slider = 100)
app$setInputs(dateRange = c("2020-12-02", "2020-12-11"))
app$setInputs(date = "2020-12-08")
app$setInputs(select = character(0))
app$setInputs(text = "")
app$snapshot()

app$setInputs(current_theme =  "flatly")
app$snapshot()
app$setInputs(text = "RStudio")
app$setInputs(select = "Michigan")
app$setInputs(date = "2020-12-24")
app$setInputs(dateRange = c("2020-12-11", "2020-12-10"))
app$setInputs(dateRange = c("2020-12-11", "2020-12-12"))
app$setInputs(slider = 0)
app$setInputs(slider = 1)
app$setInputs(checkbox = TRUE)
app$setInputs(checkboxGroup = "B")
app$setInputs(radio = "B")
app$snapshot()
app$setInputs(radio = "A")
app$setInputs(checkboxGroup = c("A", "B"))
app$setInputs(checkbox = FALSE)
app$setInputs(slider = 100)
app$setInputs(dateRange = c("2020-12-02", "2020-12-11"))
app$setInputs(date = "2020-12-08")
app$setInputs(select = character(0))
app$setInputs(text = "")
app$snapshot()

app$setInputs(current_theme =  "minty")
app$snapshot()
app$setInputs(text = "RStudio")
app$setInputs(select = "Michigan")
app$setInputs(date = "2020-12-24")
app$setInputs(dateRange = c("2020-12-11", "2020-12-10"))
app$setInputs(dateRange = c("2020-12-11", "2020-12-12"))
app$setInputs(slider = 0)
app$setInputs(slider = 1)
app$setInputs(checkbox = TRUE)
app$setInputs(checkboxGroup = "B")
app$setInputs(radio = "B")
app$snapshot()
app$setInputs(radio = "A")
app$setInputs(checkboxGroup = c("A", "B"))
app$setInputs(checkbox = FALSE)
app$setInputs(slider = 100)
app$setInputs(dateRange = c("2020-12-02", "2020-12-11"))
app$setInputs(date = "2020-12-08")
app$setInputs(select = character(0))
app$setInputs(text = "")
app$snapshot()
