app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

# Start with default state
app$snapshot()
app$setInputs(text = "R")
app$setInputs(text = "RStudio")
app$setInputs(select = "Michigan")
app$setInputs(date = "2020-12-22")
app$setInputs(dateRange = c("2020-12-11", "2020-12-10"))
app$setInputs(dateRange = c("2020-12-11", "2020-12-11"))
app$setInputs(slider = 100)
app$setInputs(slider = 97)
app$setInputs(slider = 99)
app$setInputs(checkbox = TRUE)
app$setInputs(checkboxGroup = "B")
app$setInputs(radio = "B")
# Test with all options fulfilled except the file upload
app$snapshot()
app$setInputs(radio = "A")
app$setInputs(checkboxGroup = c("A", "B"))
app$setInputs(checkbox = FALSE)
app$setInputs(slider = 30)
app$setInputs(dateRange = c("2020-12-02", "2020-12-11"))
app$setInputs(date = "2020-12-09")
app$setInputs(select = character(0))
app$setInputs(text = "")
# Test with every input failing to meet criteria
app$snapshot()
