name: runTests Matrix

on:
  push:
    branches:
      - main
      - ghactions
  pull_request:
    branches:
      - main
  # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule
  # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_16
  schedule:
    - cron:  '0 8 * * 1-5' # every work night (delayed 2 hrs)
  repository_dispatch:
    types:
      - all
      - shinytest
      - ci

jobs:
  pre_check:
    uses: ./.github/workflows/ci-precheck.yml
  config:
    uses: ./.github/workflows/ci-config.yml
    needs: precheck



  ubuntu-release:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.release }}
      os: ${{ needs.config.outputs.ubuntu }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  ubuntu-oldrel-1:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel1 }}
      os: ${{ needs.config.outputs.ubuntu }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
