name: runTests Matrix

on:
  push:
    branches:
      - main
      - ghactions
  pull_request:
    branches:
      - main
  # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule
  # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_16
  schedule:
    - cron:  '0 8 * * 1-5' # every work night (delayed 2 hrs)
  repository_dispatch:
    types:
      - all
      - shinytest
      - ci

jobs:
  precheck:
    uses: ./.github/workflows/ci-precheck.yml
  config:
    uses: ./.github/workflows/ci-config.yml
    needs: precheck


  test:
    needs:
      - config

    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        os:
          - ${{ needs.config.outputs.ubuntu }}
          - ${{ needs.config.outputs.mac }}
          - ${{ needs.config.outputs.windows }}
        r-version:
          - ${{ needs.config.outputs.release }}
          - ${{ needs.config.outputs.oldrel1 }}
          - ${{ needs.config.outputs.oldrel2 }}
          - ${{ needs.config.outputs.oldrel3 }}
          - ${{ needs.config.outputs.oldrel4 }}

    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ matrix.r-version }}
      os: ${{ matrix.os }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
