name: runTests Matrix

on:
  push:
    branches:
      - main
      - ghactions
  pull_request:
    branches:
      - main
  # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule
  # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_16
  schedule:
    - cron:  '0 8 * * 1-5' # every work night (delayed 2 hrs)
  repository_dispatch:
    types:
      - all
      - shinytest
      - ci

jobs:
  precheck:
    uses: ./.github/workflows/ci-precheck.yml
  config:
    uses: ./.github/workflows/ci-config.yml
    needs: precheck



  macos-release:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.release }}
      os: ${{ needs.config.outputs.macos }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  macos-oldrel-1:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel1 }}
      os: ${{ needs.config.outputs.macos }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  macos-oldrel-2:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel2 }}
      os: ${{ needs.config.outputs.macos }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  macos-oldrel-3:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel3 }}
      os: ${{ needs.config.outputs.macos }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  macos-oldrel-4:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel4 }}
      os: ${{ needs.config.outputs.macos }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}


  ubuntu-release:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.release }}
      os: ${{ needs.config.outputs.ubuntu }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  ubuntu-oldrel-1:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel1 }}
      os: ${{ needs.config.outputs.ubuntu }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  ubuntu-oldrel-2:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel2 }}
      os: ${{ needs.config.outputs.ubuntu }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  ubuntu-oldrel-3:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel3 }}
      os: ${{ needs.config.outputs.ubuntu }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  ubuntu-oldrel-4:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel4 }}
      os: ${{ needs.config.outputs.ubuntu }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}


  windows-release:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.release }}
      os: ${{ needs.config.outputs.windows }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  windows-oldrel-1:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel1 }}
      os: ${{ needs.config.outputs.windows }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  windows-oldrel-2:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel2 }}
      os: ${{ needs.config.outputs.windows }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  windows-oldrel-3:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel3 }}
      os: ${{ needs.config.outputs.windows }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  windows-oldrel-4:
    needs: config
    uses: ./.github/workflows/ci-runtests-os.yml
    with:
      r-version: ${{ needs.config.outputs.oldrel4 }}
      os: ${{ needs.config.outputs.windows }}
      cache-version: ${{ needs.config.outputs.cache-version }}
    secrets:
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
