name: Docker

on:
  push:
    branches:
      - docker
      - ghactions
  # # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule
  # schedule:
  #   - cron:  '0 6 * * 0-4' # every work night at ~ midnight central time
  repository_dispatch:
    types:
      - all
      - docker


jobs:
  docker:
    name: ${{ matrix.config.type }}-${{ matrix.r }}${{ matrix.extra_base_tag }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:

        cache:
          # The APPS_SHA is dynamically found below and sent in at the same time as SHINYCORECI_SHA value
          # Cache as much as possible!
          - ${{ github.event_name == 'push' }}
          # - false

        r:
          # - 3.5
          - 3.6

        # shinycoreci_sha: master
        shinycoreci_sha:
          - shiny-1.4.0.1

        # extra_base_tag:
        extra_base_tag:
          - "-rc_v1.4.0.1"


        config:

        - name: Bionic
          workdir: Docker/ubuntu
          type: bionic
          aws_build_machine: ubuntu-14.04

        - name: Xenial
          workdir: Docker/ubuntu
          type: xenial
          aws_build_machine: ubuntu-14.04

        - name: Centos7
          workdir: Docker/centos
          type: centos7
          aws_build_machine: centos6.3


    steps:
    - uses: actions/checkout@master

    - name: Get apps sha
      shell: bash
      id: apps
      run: |
        SHA=${{ github.event.pull_request.head.sha }}
        if [[ -z "$SHA" ]]; then
          SHA=${{ github.sha }}
        fi
        echo $SHA
        SHORT_SHA=${SHA:0:7}
        echo $SHORT_SHA
        echo "::set-output name=sha::$SHORT_SHA"

    # # https://github.com/marketplace/actions/publish-docker
    # - name: Base
    #   uses: elgohr/Publish-Docker-Github-Action@2.12
    #   with:
    #     name: rstudio/shinycoreci
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    #     cache: ${{ matrix.cache }}
    #     workdir: ${{ matrix.config.workdir }}
    #     buildargs: "R_VERSION=${{ matrix.r }},RELEASE=${{ matrix.config.type }},APPS_SHA=${{ steps.apps.outputs.sha }},SHINYCORECI_SHA=${{ matrix.shinycoreci_sha }},GITHUB_PAT=${{ secrets.GITHUB_PAT }}"
    #     tags: "base-${{ matrix.r }}-${{ matrix.config.type }}${{ matrix.extra_base_tag }}"


    # # https://github.com/marketplace/actions/publish-docker
    # - name: SSO
    #   uses: elgohr/Publish-Docker-Github-Action@2.12
    #   with:
    #     name: rstudio/shinycoreci
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    #     cache: ${{ matrix.cache }}
    #     workdir: ${{ matrix.config.workdir }}_sso
    #     buildargs: "R_VERSION=${{ matrix.r }},RELEASE=${{ matrix.config.type }},EXTRA_BASE_TAG=${{ matrix.extra_base_tag }}"
    #     tags: "sso-${{ matrix.r }}-${{ matrix.config.type }}${{ matrix.extra_base_tag }}"


    # https://github.com/marketplace/actions/publish-docker
    - name: SSP
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: rstudio/shinycoreci
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: ${{ matrix.cache }}
        workdir: ${{ matrix.config.workdir }}_ssp
        # ignoring build arg *_AWS_BUILD_MACHINE as it's consistent
        buildargs: "R_VERSION=${{ matrix.r }},RELEASE=${{ matrix.config.type }},SSP_LICENSE=${{ secrets.SSP_LICENSE }},EXTRA_BASE_TAG=${{ matrix.extra_base_tag }}"
        tags: "ssp-${{ matrix.r }}-${{ matrix.config.type }}${{ matrix.extra_base_tag }}"
