name: Docker

on:
  push:
    branches:
      - docker
      - ghactions
  # # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule
  # schedule:
  #   - cron:  '0 6 * * 0,3' # every sunday and wednesday night at ~ midnight central time
  repository_dispatch:
    types:
      - all
      - docker


jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    # https://github.com/marketplace/actions/publish-docker
    - name: Publish Base
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: rstudio/shinycoreci
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        # cache: ${{ github.event_name == 'push' }}
        cache: false
        workdir: Docker/ubuntu
        # ARG R_VERSION=3.6
        # ARG RELEASE=bionic
        # ARG GITHUB_PAT=NOTSUPPLIED
        # ARG APPS_SHA=master
        # ARG SHINYCORECI_SHA=docker
        buildargs: "R_VERSION=3.6,RELEASE=bionic,APPS_SHA=master,SHINYCORECI_SHA=docker,GITHUB_PAT=${{ secrets.GITHUB_PAT }}"
        tags: "base-3.6-bionic"


    # https://github.com/marketplace/actions/publish-docker
    - name: Publish SSO
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: rstudio/shinycoreci
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: false
        workdir: Docker/ubuntu_sso
        # ARG R_VERSION=3.6
        # ARG RELEASE=bionic
        # ARG AWS_BUILD_MACHINE=ubuntu-14.04
        buildargs: "R_VERSION=3.6,RELEASE=bionic"
        tags: "sso-3.6-bionic"


  centos:
    name: Centos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    # https://github.com/marketplace/actions/publish-docker
    - name: Publish Base
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: rstudio/shinycoreci
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: false
        workdir: Docker/centos
        # ARG R_VERSION=3.6
        # ARG GITHUB_PAT=NOTSUPPLIED
        # ARG APPS_SHA=master
        # ARG SHINYCORECI_SHA=docker
        buildargs: "R_VERSION=3.6,APPS_SHA=master,SHINYCORECI_SHA=docker,GITHUB_PAT=${{ secrets.GITHUB_PAT }}"
        tags: "base-3.6-centos7"


    # https://github.com/marketplace/actions/publish-docker
    - name: Publish SSO
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: rstudio/shinycoreci
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: false
        workdir: Docker/centos_sso
        # ARG R_VERSION=3.6
        buildargs: "R_VERSION=3.6"
        tags: "sso-3.6-centos7"
