app <- ShinyDriver$new("../../", seed = 100, shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(freq = 35)
app$setInputs(max = 250)
app$setInputs(selection = "merchant")
app$snapshot()
app$setInputs(selection = "romeo")
app$snapshot()
app$setInputs(update = "click")
app$setInputs(freq = 10)
app$snapshot()
